const ShopActionTypes = {
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLETCIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLETCIONS_FAILURE",
};

export default ShopActionTypes;